language: python
os:
  - linux
  - windows
python:
  - "3.6"
cache: pip
install:
  - pip install git+https://github.com/hcv-shared/pynucamino@master#egg=pynucamino
  - pip install -r test-requirements.txt
script:
  - python setup.py flake8
  - python setup.py test
notifications:
  email:
    on_failure: change
